name: Docs Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    # Only run tests if there is no [skipci] or [skip ci] in the commit message
    if: |
      !startsWith(github.event.head_commit.message, '[skip ci]') &&
      !startsWith(github.event.head_commit.message, '[skipci]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Install basic dependencies (MPI, FFTW, IMO)
        run: |
          ./bin/install-deps.sh ${{ matrix.mpi }}
          mkdir -p $HOME/.config/litebird_imo
          echo -e "[[repositories]]\nlocation = \"$(pwd)/test/mock_imo/\"\nname = \"Mock IMO\"" | tee $HOME/.config/litebird_imo/imo.toml

      - name: Install dev and docs dependencies
        run: |
          EXTRAS="--extra dev --extra docs"
          uv sync --locked ${EXTRAS}

      - name: Test code examples in the documentation
        run: |
          set -euo pipefail
          uv run make -C docs/ doctest
